### ISSUE TITLE
ConstraintLayout里面有两个SelectorImageButton, 点击一个另一个也出现点击效果

### ISSUE THREAD

**Issue by MAIMIHO** [tianzhijiexian/SelectorInjection#10]
大佬, 你好! 
ConstraintLayout里面有两个SelectorImageButton, 点击一个另一个也出现点击效果, 要怎么避免这种情况?

**Comment by a1109742518** [comment]
尝试把另一个button也加上点击事件

**Comment by kaleai** [comment]
这个问题我通过复制drawable的方案解决了，你可以拉下最新的demo测试一下。
