### ISSUE TITLE
add textcolor

### ISSUE THREAD

**Issue by moter** [tianzhijiexian/SelectorInjection#11]
按照你这个思路可以把控件文字不同状态时的颜色也加上

**Comment by kaleai** [comment]
可以是可以，但这个主要是做背景方面的工作，是通用的设计，如果是文字，那么复杂度会增加。我再考虑考虑吧

**Comment by kaleai** [comment]
没有想到好的给文字加效果的方案，有什么方案可以提一下，我尝试做一些

**Comment by kaleai** [comment]
目前想了一下text本身的selector就是可以被多处复用的，没必要针对text做代码中设置的属性。

如果有需求的话，那么可以增加：

- app:txtNormalColor 
- app:txtPressColor 
- app:txtCheckedColor 
- app:txtDisableColor

但这样的话属性就过多了，学习成本较大。

其实你可以把文字当作各式各样的形状，那么文字的颜色状态其实就是复用的，项目越做越大，这个复用的地方会越来越多，所以个人觉得定义文字的selector是有必要的。
