### ISSUE TITLE
在Android6.0上显示Bug

### ISSUE THREAD

**Issue by lujianzhao** [tianzhijiexian/SelectorInjection#13]
水波纹在Android6.0上有显示的Bug,第一次渲染会空白，当第一次点击后，才显示正常。。
引用：https://hk.saowen.com/a/0673cb03a7dc4b3d61d7b0641d60e98abd5e1e47d6f06dcbefd5a18c08cc024c

**Comment by kaleai** [comment]
我会根据这篇文章的说明，去更改一下代码的，修复后会通知到您

**Comment by kaleai** [comment]
这个库的app项目中也出现了这个问题么？可以说下你的手机型号和系统版本，因为库中就是用水波纹实现的效果，看起来和你贴的链接并无区别，代码如下：

https://github.com/tianzhijiexian/SelectorInjection/blob/master/lib/src/main/res/drawable-v21/si_ripple.xml

**Comment by lujianzhao** [comment]
测试机型：华为KTW-TL00H
测试系统：Android6.0.1
这个库的app项目也会出现这个问题，大概就是因为那份文章里说的Android6.0上的BUG导致的。那份文章的解决方案也是有点问题的，6.0系统上我怎么修改都不行，后面我的解决方案是：在6.0系统的时候不使用水波纹才解决掉。

**Comment by kaleai** [comment]
@lujianzhao 复现方式是用水波纹，但第一次点击时不出现，第二次才出现水波纹效果，时这样的么？

**Comment by lujianzhao** [comment]
复现方式：1、在Android6.0系统上使用水波纹。app:ripple="true"
显示一片空白，然后点击一下按钮，就显示正常。
![screenshot_2018-10-06-21-01-32](https://user-images.githubusercontent.com/19725196/46571659-843d4a80-c9ab-11e8-84a4-1f40d857a34e.png)
![screenshot_2018-10-06-21-01-27](https://user-images.githubusercontent.com/19725196/46571661-87d0d180-c9ab-11e8-9467-32b750830fa1.png)

**Comment by lujianzhao** [comment]
我想到了一个非常糟糕的解决办法😂
![b09f628b-0e4b-4a49-a54e-f2cf2eacfd4c](https://user-images.githubusercontent.com/19725196/46571987-388d9f80-c9b1-11e8-833d-0e0c4bd0cf77.png)
![c5379343-178a-494e-8c6e-701deccfbf8b](https://user-images.githubusercontent.com/19725196/46571988-39263600-c9b1-11e8-892c-229506f0a992.png)

**Comment by kaleai** [comment]
ok 我明天看一下

**Comment by kaleai** [comment]
hello，我想问下除了华为你那里还有什么别的测试手机么，比如小米、魅族、oppo之类的，我这里用一加并没有复现这个问题，所以麻烦更换相爱别的测试机看看，如果也有问题可以报上型号。

**Comment by lujianzhao** [comment]
目前我也只是发现华为存在着这个问题。

**Comment by kaleai** [comment]
华为这真的是…… 我找下我这里的机器吧，我先抽空看看

**Comment by lujianzhao** [comment]
谢谢，麻烦了。。
这个问题也困扰了我好久，我实在想不出好的解决方案了。

**Comment by kaleai** [comment]
460412008 可以加qq一起看一下这个问题

**Comment by kaleai** [comment]
![image](https://user-images.githubusercontent.com/9552155/46599001-9983b780-cb18-11e8-8dfb-bd046d684c46.png)

![image](https://user-images.githubusercontent.com/9552155/46599177-1ca50d80-cb19-11e8-8ecb-fc2f4297c53a.png)

**Comment by kaleai** [comment]
fixed https://github.com/tianzhijiexian/SelectorInjection/commit/b36171156afe40268d1c2c544d3f5590abadb7fd
