### ISSUE TITLE
水纹会闪出现条纹

### ISSUE THREAD

**Issue by 0xm1nam0** [tianzhijiexian/SelectorInjection#2]
MX4 Pro
Android:5.1.1

**Comment by kaleai** [comment]
截个图吧，我好看一下。

**Comment by 0xm1nam0** [comment]
![qq 20160513140826](https://cloud.githubusercontent.com/assets/13305202/15239365/7c274ac0-1914-11e6-961e-d4cbe8b2e33b.jpg)
其中一帧，闪的很快。

**Comment by kaleai** [comment]
好诡异，你用官方的做法加个水波纹试试看。会不会有这样的情况

**Comment by kaleai** [comment]
@WeissWill 我更新了一下，你再看看呢？看看有没有解决

**Comment by 0xm1nam0** [comment]
还是会哦，不停闪烁条纹，感觉点击接触面积小点的时候触发率低点

**Comment by kaleai** [comment]
460412008@qq.com qq聊吧

**Comment by JakeWoki** [comment]
部分手机有，应该是硬件加速的问题

**Comment by kaleai** [comment]
@0xm1nam0 你看看是否是硬件加速的问题

**Comment by kaleai** [comment]
@0xm1nam0 目前更新了水波纹的实现，可以测试看看
