### ISSUE TITLE
shape描边相互影响

### ISSUE THREAD

**Issue by demoface** [tianzhijiexian/SelectorInjection#5]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#ff0099cc"
    android:orientation="vertical">

        <kale.ui.view.SelectorTextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:text="0000"
            android:textColor="#333333"
            android:textSize="30sp"
            app:normalColor="@android:color/darker_gray"
            app:normalDrawable="@drawable/btn_oval_shape"
            app:normalStrokeColor="#ff0000"
            app:normalStrokeWidth="2dp" />

        <kale.ui.view.SelectorButton
            android:id="@+id/sstv"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_gravity="center_horizontal"
            android:gravity="center"
            android:text="Click Me"
            android:textColor="@android:color/white"
            android:textSize="20sp"
            app:normalColor="#9BD000"
            app:normalDrawable="@drawable/btn_oval_shape" />
</LinearLayout>

第一个Textview的描边和颜色， 在第二个上面也会出现

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@android:color/transparent"/>
    <corners android:radius="8dp"/>
</shape>

**Comment by demoface** [comment]
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@android:color/transparent"/>
    <corners android:radius="8dp"/>
</shape>

**Comment by demoface** [comment]
`<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@android:color/transparent"/>
    <corners android:radius="8dp"/>
</shape>`

**Comment by kaleai** [comment]
这个是因为drawable内部复用的问题，我解决一下。

**Comment by kaleai** [comment]
已经fix
