### ISSUE TITLE
No resource identifier found for attribute

### ISSUE THREAD

**Issue by MAIMIHO** [tianzhijiexian/SelectorInjection#8]
作者你好:
直接依赖`compile 'com.github.tianzhijiexian:SelectorInjection:1.0.4'`
会提示No resource identifier found for attribute 'drawableLeftTint' in package 'kale.selectorinjection'
![image](https://cloud.githubusercontent.com/assets/18633356/23577168/8cc7070e-00f3-11e7-84e3-6e37be4417f9.png)
是因为attrs.xml命名为了values.xml的原因吗? 
添加attrs中属性到工程的attrs中可以正常使用.

**Comment by kaleai** [comment]
看起来是 drawableLeftTint 这个属性被移除掉了，你看看textview有没有这个属性。

**Comment by MAIMIHO** [comment]
TextView没有drawableLeftTint 这个属性
    minSdkVersion = 16
    targetSdkVersion = 25
    compileSdkVersion = 25

**Comment by kaleai** [comment]
demo跑起来是好的么？

**Comment by MAIMIHO** [comment]
demo能正常跑起来, 但是我将dependencies做出如下修改会提示同样错误. 
dependencies {
//    compile project(':injection')
    compile 'com.github.tianzhijiexian:SelectorInjection:1.0.4'
    compile 'com.android.support:appcompat-v7:24.2.0'
}

**Comment by kaleai** [comment]
我看一下是不是版本的问题

**Comment by kaleai** [comment]
分析后发现打包后的文件中属性如下：  

![image](https://cloud.githubusercontent.com/assets/9552155/23643739/8080ff3e-033e-11e7-9dfd-7901760a4bf5.png)

于是可以知道打包没有打进去需要的属性，我更换了打包的方式，你可以试下：

    compile 'com.github.tianzhijiexian:SelectorInjection:6fbb3e7685'

结果请告知！ @MAIMIHO 

https://github.com/tianzhijiexian/SelectorInjection/commit/6fbb3e76859696f5a1b13b3bf73e84db48118921

**Comment by MAIMIHO** [comment]
使用
`compile 'com.github.tianzhijiexian:SelectorInjection:6fbb3e7685'`
能正常使用了. 
![image](https://cloud.githubusercontent.com/assets/18633356/23645253/2eaea8c0-0346-11e7-87db-420beb8d37d1.png)

**Comment by kaleai** [comment]
@MAIMIHO 我更新一个版本

**Comment by kaleai** [comment]
https://github.com/tianzhijiexian/SelectorInjection/releases/tag/1.0.5
